describe("Programming suite", function() {
    /*
    it(`Input:
    queryType:
    ["insert", 
     "insert", 
     "addToValue", 
     "addToKey", 
     "get"]
    query:
    [[1,2], 
     [2,3], 
     [2], 
     [1], 
     [3]]
    Expected Output:
    5`, function() {
        expect(solution(["insert",
            "insert",
            "addToValue",
            "addToKey",
            "get"
        ], [
            [1, 2],
            [2, 3],
            [2],
            [1],
            [3]
        ])).toEqual(5);
    });

    it(`Input:
    queryType:
    ["addToKey", 
     "addToKey", 
     "insert", 
     "addToValue", 
     "addToValue", 
     "get", 
     "addToKey", 
     "insert", 
     "addToKey", 
     "addToValue"]
    query:
    [[-3], 
     [-1], 
     [0,-3], 
     [3], 
     [-1], 
     [0], 
     [-1], 
     [-4,-5], 
     [-1], 
     [-4]]
    Expected Output:
    -1`, function() {
        expect(solution(["addToKey",
            "addToKey",
            "insert",
            "addToValue",
            "addToValue",
            "get",
            "addToKey",
            "insert",
            "addToKey",
            "addToValue"
        ], [
            [-3],
            [-1],
            [0, -3],
            [3],
            [-1],
            [0],
            [-1],
            [-4, -5],
            [-1],
            [-4]
        ])).toEqual(-1);
    });
*/
    it(`Input:
    queryType:
    ["addToKey", 
     "addToValue", 
     "insert", 
     "addToValue", 
     "addToKey", 
     "get", 
     "insert", 
     "addToValue", 
     "addToValue", 
     "get", 
     "insert", 
     "addToKey", 
     "get", 
     "addToKey", 
     "addToKey", 
     "addToValue", 
     "insert", 
     "addToValue", 
     "get", 
     "addToKey", 
     "addToKey", 
     "insert", 
     "addToValue", 
     "addToKey", 
     "addToValue", 
     "insert", 
     "get", 
     "addToKey", 
     "addToValue", 
     "get", 
     "get", 
     "get", 
     "addToValue", 
     "addToValue", 
     "get", 
     "get", 
     "insert", 
     "insert", 
     "addToKey", 
     "insert", 
     "addToValue", 
     "addToValue", 
     "addToKey", 
     "addToValue", 
     "addToValue", 
     "get", 
     "addToValue", 
     "addToKey", 
     "get", 
     "addToValue", 
     "insert", 
     "get", 
     "get", 
     "get", 
     "addToValue", 
     "addToValue", 
     "get", 
     "addToKey", 
     "get", 
     "addToKey", 
     "addToValue", 
     "get", 
     "get", 
     "addToKey", 
     "insert", 
     "addToKey", 
     "get", 
     "addToKey", 
     "addToValue", 
     "addToKey", 
     "insert", 
     "addToKey", 
     "addToValue", 
     "addToKey", 
     "addToValue", 
     "addToValue", 
     "get", 
     "get", 
     "addToKey", 
     "insert", 
     "get", 
     "get", 
     "addToKey", 
     "insert", 
     "addToKey", 
     "addToValue", 
     "addToKey", 
     "insert", 
     "addToValue", 
     "get", 
     "get", 
     "insert", 
     "get", 
     "get", 
     "addToValue", 
     "get", 
     "addToValue", 
     "insert", 
     "addToKey", 
     "addToValue"]
    query:
    [
        [ 32 ],      [ -4 ],       [ 32, -42 ], [ 19 ],       [ -45 ],
        [ -13 ],     [ 29, -29 ],  [ -50 ],     [ 40 ],       [ -13 ],
        [ 39, -11 ], [ -47 ],      [ -60 ],     [ 16 ],       [ -14 ],
        [ 45 ],      [ -34, 17 ],  [ -12 ],     [ -6 ],       [ 2 ],
        [ -33 ],     [ -33, -6 ],  [ 40 ],      [ -14 ],      [ 30 ],
        [ -13, 11 ], [ -61 ],      [ -1 ],      [ -40 ],      [ -62 ],
        [ -52 ],     [ -52 ],      [ -18 ],     [ -2 ],       [ -104 ],
        [ -104 ],    [ -27, -13 ], [ 28, -17 ], [ -40 ],      [ 39, -1 ],
        [ -40 ],     [ 25 ],       [ -39 ],     [ 46 ],       [ 27 ],
        [ -51 ],     [ -33 ],      [ 11 ],      [ -130 ],     [ 37 ],
        [ 37, -20 ], [ -95 ],      [ -95 ],     [ 11 ],       [ 37 ],
        [ -2 ],      [ -40 ],      [ -47 ],     [ -167 ],     [ 13 ],
        [ -41 ],     [ -164 ],     [ -206 ],    [ 1 ],        [ 14, 19 ],
        [ 23 ],      [ -92 ],      [ 39 ],      [ 25 ],       [ -33 ],
        [ -5, -34 ], [ -45 ],      [ 23 ],      [ 2 ],        [ -13 ],
        [ -12 ],     [ -163 ],     [ -142 ],    [ -4 ],       [ -34, -44 ],
        [ -91 ],     [ -34 ],      [ 34 ],      [ -49, -19 ], [ 9 ],
        [ -24 ],     [ 42 ],       [ 12, -1 ],  [ 43 ],       [ -114 ],
        [ 33 ],      [ -12, -15 ], [ 81 ],      [ -6 ],       [ -27 ],
        [ 51 ],      [ -50 ],      [ -36, -9 ], [ 24 ],       [ 40 ]
      ]
    Expected Output:
    1069`, function() {
        expect(solution(
            ["addToKey", 
     "addToValue", 
     "insert", 
     "addToValue", 
     "addToKey", 
     "get", 
     "insert", 
     "addToValue", 
     "addToValue", 
     "get", 
     "insert", 
     "addToKey", 
     "get", 
     "addToKey", 
     "addToKey", 
     "addToValue", 
     "insert", 
     "addToValue", 
     "get", 
     "addToKey", 
     "addToKey", 
     "insert", 
     "addToValue", 
     "addToKey", 
     "addToValue", 
     "insert", 
     "get", 
     "addToKey", 
     "addToValue", 
     "get", 
     "get", 
     "get", 
     "addToValue", 
     "addToValue", 
     "get", 
     "get", 
     "insert", 
     "insert", 
     "addToKey", 
     "insert", 
     "addToValue", 
     "addToValue", 
     "addToKey", 
     "addToValue", 
     "addToValue", 
     "get", 
     "addToValue", 
     "addToKey", 
     "get", 
     "addToValue", 
     "insert", 
     "get", 
     "get", 
     "get", 
     "addToValue", 
     "addToValue", 
     "get", 
     "addToKey", 
     "get", 
     "addToKey", 
     "addToValue", 
     "get", 
     "get", 
     "addToKey", 
     "insert", 
     "addToKey", 
     "get", 
     "addToKey", 
     "addToValue", 
     "addToKey", 
     "insert", 
     "addToKey", 
     "addToValue", 
     "addToKey", 
     "addToValue", 
     "addToValue", 
     "get", 
     "get", 
     "addToKey", 
     "insert", 
     "get", 
     "get", 
     "addToKey", 
     "insert", 
     "addToKey", 
     "addToValue", 
     "addToKey", 
     "insert", 
     "addToValue", 
     "get", 
     "get", 
     "insert", 
     "get", 
     "get", 
     "addToValue", 
     "get", 
     "addToValue", 
     "insert", 
     "addToKey", 
     "addToValue"], [
            [32],
            [-4],
            [32, -42],
            [19],
            [-45],
            [-13],
            [29, -29],
            [-50],
            [40],
            [-13],
            [39, -11],
            [-47],
            [-60],
            [16],
            [-14],
            [45],
            [-34, 17],
            [-12],
            [-6],
            [2],
            [-33],
            [-33, -6],
            [40],
            [-14],
            [30],
            [-13, 11],
            [-61],
            [-1],
            [-40],
            [-62],
            [-52],
            [-52],
            [-18],
            [-2],
            [-104],
            [-104],
            [-27, -13],
            [28, -17],
            [-40],
            [39, -1],
            [-40],
            [25],
            [-39],
            [46],
            [27],
            [-51],
            [-33],
            [11],
            [-130],
            [37],
            [37, -20],
            [-95],
            [-95],
            [11],
            [37],
            [-2],
            [-40],
            [-47],
            [-167],
            [13],
            [-41],
            [-164],
            [-206],
            [1],
            [14, 19],
            [23],
            [-92],
            [39],
            [25],
            [-33],
            [-5, -34],
            [-45],
            [23],
            [2],
            [-13],
            [-12],
            [-163],
            [-142],
            [-4],
            [-34, -44],
            [-91],
            [-34],
            [34],
            [-49, -19],
            [9],
            [-24],
            [42],
            [12, -1],
            [43],
            [-114],
            [33],
            [-12, -15],
            [81],
            [-6],
            [-27],
            [51],
            [-50],
            [-36, -9],
            [24],
            [40]
        ])).toEqual(1069);
    });
});